org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20

# Environment Properties
minecraft_version=26.1
minecraft_version_range=[26.1, 26.2)
neo_version=26.1.0.1-beta

## Mod Properties
mod_id=musings
mod_name=Musings
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.mystic.musings