pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        mavenCentral()
    }

    resolutionStrategy {
        eachPlugin {
            switch (requested.id.id) {
                case "net.minecraftforge.gradle":
                    useModule("net.minecraftforge.gradle:net.minecraftforge.gradle.gradle.plugin:${requested.version}")
                    break

                case "org.spongepowered.mixin":
                    useModule("org.spongepowered:mixingradle:${requested.version}")
                    break
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'musings'
